version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: foodhub-mysql
    environment:
      MYSQL_DATABASE: foodhub
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    networks:
      - foodhub-net
    restart: always

  foodhub-app:
    build: .
    container_name: foodhub-app
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: foodhub
    depends_on:
      - mysql
    networks:
      - foodhub-net
    restart: always

volumes:
  mysql-data:

networks:
  foodhub-net:
